# USB通信とBluetoothの両方を有効にする
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# 単体動作を保証
CONFIG_ZMK_SPLIT=n

# デバッグログ（必要に応じて）
CONFIG_ZMK_USB_LOGGING=y

# ディスプレイ機能を有効化
CONFIG_ZMK_DISPLAY=y

# I2C通信のデバッグログを有効化
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_I2C_DUMP_MESSAGES=y