# USB通信とBluetoothの両方を有効にする
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# 単体動作を保証
CONFIG_ZMK_SPLIT=n

# デバッグログ
CONFIG_ZMK_USB_LOGGING=y

# ディスプレイ機能を有効化
CONFIG_ZMK_DISPLAY=n

# 表示処理を専用のスレッドで行い、キー入力を優先させる
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# 128x64用設定のなごりですが、安定のために維持
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2048

# I2C通信のハングアップ防止
CONFIG_I2C_NRFX_TRANSFER_TIMEOUT=100